In [1]:
import numpy as np
marks = np.array([60,80,75,90])
print(marks)

[60 80 75 90]


In [3]:
#vectorization
bonus_marks = marks+5
print(bonus_marks)

[65 85 80 95]


In [6]:
print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))

76.25
90
60


In [9]:
acc = np.array([0.85, 0.92, 0.78, 0.95, 0.88])
per = acc*100
print(per)
print(np.mean(per))


[85. 92. 78. 95. 88.]
87.6


In [12]:
data = np.array([[10,20,30],[40,50,60]])
print(data)

[[10 20 30]
 [40 50 60]]


In [13]:
data.shape

(2, 3)

In [19]:
data = np.array([[1,2],[3,4]])
print(data)
print(data.shape)
print(data *10)
print(data[0,0])

[[1 2]
 [3 4]]
(2, 2)
[[10 20]
 [30 40]]
1
